### ISSUE TITLE
Crash during catchup with trusted hash

### ISSUE THREAD

**Issue by XeZZoR** [CasperLabs/casper-node#498]
[message.txt](https://github.com/CasperLabs/casper-node/files/5497956/message.txt)

See the attached file for log from the node.
Crash can be reproduced by installing everything on a clean box and syncing the node with trusted hashes. 

Tested: Around 20 Resyncs
Crashes: 6
Tested with different trusted hashes - Crash is not always happening (So hash is valid)
One of the hashes tested with: `3b0e4ae85f096b0be2e28402c3f32c471d0f5f4a470d2709c731e0febf3d26ec`
Environment: Ubuntu 18.04 (Docker - can provide build scripts)

**Comment by XeZZoR** [comment]
Attaching source Setup. To reproduce:

Change the trusted hash in config/config.toml

```
docker volume create clkeys
./rebuild.sh
docker logs -f capser
```

This should build the container and show logs. The image build takes quite a while and if the era switches in between the trusted hash is invalid to catchup. In that case just exchange the hash and run ./rebuild.sh again it nukes the state completely despite the generated keys.
[casperdocker.zip](https://github.com/CasperLabs/casper-node/files/5502227/casperdocker.zip)

**Comment by afck** [comment]
My theory is that some node in the network was reusing a storage directory from a previous network. That's the only way I could reproduce something akin to this issue. https://github.com/CasperLabs/casper-node/pull/508 should address this: If a peer sends us a block with the wrong parent, we retry with another peer.
(That also means that if _we_ are the ones joining the network with outdated storage, the node would give up after a while: `Consensus shutting down due to inability to participate in the network`.)

**Comment by XeZZoR** [comment]
I am very confident this is not the case since I ran it on a complete new server and was able to reproduce it.

**Comment by afck** [comment]
Yes, but another node in the network could have used an oudated storage directory, and sent an invalid block to your node?

**Comment by XeZZoR** [comment]
Ah I got it sorry I misread your comment above. That is very possible and would be inline with the log message too.
