### ISSUE TITLE
Bid contract deployment with an error

### ISSUE THREAD

**Issue by Alive29** [CasperLabs/casper-node#568]
I've tried to deploy a contract from newly fresh compiled sources but  the deployment was completed with an error.
I've tried to use the contract that was assembled when starting Delta-1 - everything works fine

The same error was in delta-2
``
"error_message": "Interpreter error: host module doesn't export function with name casper_call_contract"
``

**Comment by XeZZoR** [comment]
Example in current detla-3

`casper-client get-deploy 7505126c552ddb638e5ad4ea51c3d55cdad5244c6ef6eee9be38ca5a855ed137 --node-address http://localhost:7777`

The issue is in the instructions on bonding. It should mention to checkout the correct tag `git checkout release-1.6.0` solves the issue. (Recompile the contracts)

**Comment by MParlikar** [comment]
Correct - the contracts need to be re-compiled.
